<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net35;netstandard2.1</TargetFrameworks>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <AssemblyName>ManagedBass</AssemblyName>
    <Version>3.0.0</Version>
    <Authors>MathewSachin</Authors>
    <Description>.Net wrapper for un4seen BASS audio library</Description>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <Import Project="..\..\Bass\Shared\Shared.projitems" Label="Shared" />

  <ItemGroup Condition="'$(TargetFramework)' == 'net35'">
    <PackageReference Include="AsyncBridge" Version="0.3.1" />
    <PackageReference Include="NetLegacySupport.Tuple" Version="1.1.1" />
  </ItemGroup>

</Project>
