<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net35</TargetFramework>
    <AssemblyName>ManagedBass</AssemblyName>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <DefineConstants>__DESKTOP__</DefineConstants>
    <Version>3.0.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AsyncBridge" Version="0.3.1" />
    <PackageReference Include="NetLegacySupport.Tuple" Version="1.1.1" />
  </ItemGroup>

  <Import Project="..\Shared\Shared.projitems" Label="Shared" />

</Project>
